### ISSUE TITLE
Django 1.9.4 warning

### ISSUE THREAD

**Issue by johndark** [recamshak/django-debug-panel#21]
Hi,
I got a message below (python 2.7+django 1.9.4)

> [WARNING:py.warnings]**[**init**.py:107]: C:\Python27\lib\site-packages\debug_panel\urls.py:15: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got debug_data). Pass the callable instead.

**Comment by recamshak** [comment]
This is fixed in version 0.8.3
