### ISSUE TITLE
Latest version not on PyPi

### ISSUE THREAD

**Issue by joshblum** [recamshak/django-debug-panel#22]
```
$ pip install django-debug-panel==0.8.3
Collecting django-debug-panel==0.8.3
  Could not find a version that satisfies the requirement django-debug-panel==0.8.3 (from versions: 0.5.1, 0.5.2, 0.5.3, 0.5.5, 0.5.6, 0.5.7, 0.5.8, 0.5.9, 0.6.0, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.8.2)
No matching distribution found for django-debug-panel==0.8.3
$
```

The version bump commit pushes to `0.8.3` https://github.com/recamshak/django-debug-panel/commit/ab867ac7aee9eebd1456fb2d73e7463caef5b0ea and pypi also thinks that this version is available https://pypi.python.org/pypi/django-debug-panel/0.8.3

Any ideas why `pip` can't find this version?

**Comment by DheerendraRathor** [comment]
I guess @recamshak has not uploaded the tar.gz or path to download 0.8.3 version.

@recamshak Please upload 0.8.3 to pypi.

**Comment by recamshak** [comment]
Sorry for being so late, it should be fixed now!
